name: Docker Image CI
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/TOH
    - name: Docker Login
      run: docker login -u {{secrets.DOCKERHUB_USERNAME}} -p {{secrets.DOCKERHUB_PASSWORD}}
    - name: Publish to dockerhub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/TOH
