# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test with dotnet
    #   run: dotnet test --logger trx --results-directory "TestResults"
    # - name: Upload dotnet test results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dotnet-results
    #     path: TestResults
    #   # Use always() to always run this step to publish test results when there are test failures
    #   if: ${{ always() }}
    - name: Create files for report
      run: 
        echo "title=Test Run ${{github.run_number}}" >> $GITHUB_ENV
        echo "file_name=TestReport.${{github.run_number}}.md" >> $GITHUB_ENV
    - name: Test project      
      run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
       # upload report as build artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Test Run'
        path: ${{github.workspace}}/${{env.file_name}}
    