# name: 'Test Report'
# on:
#   workflow_run:
#     workflows: ['CI']                     # runs after CI workflow
#     types:
#       - completed
# jobs:
#   report:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: dorny/test-reporter@v1.6.0
#       with:
#         artifact: dotnet-results            # artifact name
#         name: MS Tests                  # Name of the check run which will be created
#         path: '*.trx'                     # Path to test results (inside artifact .zip)
#         reporter: dotnet-trx              # Format of test results




#       #       - name: Test Reporter
#       # uses: dorny/test-reporter@v1.6.0
#       # if: success() || failure()    # run this step even if previous step failed
#       # with:
#       #   name: MS Tests            # Name of the check run which will be created
#       #   path: TestResults/*.trx    # Path to test results
#       #   reporter: dotnet-trx        # Format of test results